% Generated by MATLAB(R) 9.9 (R2020b) and LTE Toolbox 3.4 (R2020b).
% Generated on: 31-Mar-2022 15:57:55

%% Generate Downlink RMC Waveform
% Downlink RMC configuration:
cfg = struct('RC', 'R.0', ...
    'DuplexMode', 'FDD', ...
    'NCellID', 0, ...
    'TotSubframes', 10, ...
    'NumCodewords', 1, ...
    'Windowing', 0, ...
    'AntennaPort', 1);

cfg.OCNGPDSCHEnable = 'On';
cfg.OCNGPDCCHEnable = 'On';
cfg.PDSCH.TxScheme = 'Port0';
cfg.PDSCH.RNTI = 1;
cfg.PDSCH.Rho = 0;
cfg.PDSCH.RVSeq = [0 1 2 3];
cfg.PDSCH.NHARQProcesses = 8;
cfg.PDSCH.PMISet = 1;
cfg = lteRMCDL(cfg);

% input bit source:
pn = comm.PNSequence('Polynomial', 'x9+x5+1', 'InitialConditions', [zeros(1, 8) 1]);
pn.SamplesPerFrame = sum(cfg.PDSCH.TrBlkSizes(1, :));

ori_sig=[];
for i=1:27
    in = pn();
    [waveform, grid, cfg] = lteRMCDLTool(cfg, in);
    ori_sig=[ori_sig;waveform];
end
Fs = cfg.SamplingRate; 	
ori_sig=ori_sig(1:1024000,1);

save('A2_16QAM.mat','ori_sig')

