% Generated by MATLAB(R) 9.9 (R2020b) and Communications Toolbox 7.4 (R2020b).
% Generated on: 29-Mar-2022 21:08:52

%% Generate Bluetooth Low Energy Waveform
% Bluetooth Low Energy configuration:
% input bit source:
pn = comm.PNSequence('Polynomial', 'x9+x5+1', 'InitialConditions', [zeros(1, 8) 1]);
pn.SamplesPerFrame = 2056;


% waveform generation:

Fs = 8e+06; 								 % sample rate of waveform

ori_sig=[];
for i=1:80
    in = pn();
    waveform = bleWaveformGenerator(in, 'Mode', 'LE1M', ...
    'SamplesPerSymbol', 8, ...
    'ChannelIndex', 37, ...
    'AccessAddress', [0 1 1 0 1 0 1 1 0 1 1 1 1 1 0 1 1 0 0 1 0 0 0 1 0 1 1 1 0 0 0 1]');
    ori_sig=[ori_sig;waveform];
end
ori_sig=ori_sig(1:1024000,1);
save('A14.mat','ori_sig')


